#!/usr/bin/env python
import os, re, sys, shutil
import math, ROOT

sys.path.insert(1,os.path.dirname(os.path.abspath(__file__))+'/../')
from readConfg import elComandante_ini 
from readConfg import elComandante_conf

################ elComandante_ini ################
elini = elComandante_ini(debug=True)
#elini = elComandante_ini()
elini.getDefault("../elComandante.ini.default", True)
elini.listSections()
elini.listOptions("mySection")
elini.makeNewSection("mySection1")
elini.makeNewSection("mySection1")
elini.makeNewSection("mySection2")
elini.makeNewSection("mySection3")
elini.listSections()
elini.listOptions("mySection")
elini.listOptions("mySection1")
elini.listOptions("mySection2")
elini.makeNewOption("mySection1", "Opt1", "Here")
elini.makeNewOption("mySection1", "Opt2", "Here")
elini.makeNewOption("mySection2", "Opt1", "Here")
elini.listOptions("Transfer")
elini.callOption("Transfer", "user" )
elini.changeOptValue("mySection1", "Opt3", "There" )
elini.changeOptValue("mySection1", "Opt1", "There" )
elini.changeOptValue("Transfer", "user", "jtsai" )
elini.callOption("Transfer", "user" )
elini.callConfig()
elini.makeConfig()

################ elComandante_conf ################
elconf = elComandante_conf(debug=True)
#elconf = elComandante_conf()
elconf.getDefault("../elComandante.conf.default", True)
elconf.listSections()
elconf.listOptions("mySection")
elconf.makeNewSection("mySection1")
elconf.makeNewSection("mySection1")
elconf.makeNewSection("mySection2")
elconf.makeNewSection("mySection3")
elconf.listSections()
elconf.listOptions("mySection")
elconf.listOptions("mySection1")
elconf.listOptions("mySection2")
elconf.makeNewOption("mySection1", "Opt1", "Here")
elconf.makeNewOption("mySection1", "Opt2", "Here")
elconf.makeNewOption("mySection2", "Opt1", "Here")
elconf.listOptions("Transfer")
elconf.callOption("Transfer", "user" )
elconf.changeOptValue("mySection1", "Opt3", "There" )
elconf.changeOptValue("mySection1", "Opt1", "There" )
elconf.changeOptValue("Transfer", "user", "jtsai" )
elconf.callOption("Transfer", "user" )
elconf.callConfig()
elconf.makeConfig()
